/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      animation: {
        'move-letter': 'letterMove 2s infinite ease-in-out',
        blink: 'blink 1s infinite',
        'rotate-blink': 'rotateBlink 2s infinite',
        shake: 'shake 0.5s cubic-bezier(.36,.07,.19,.97) both',
        'rotate-15': 'rotate15x 15s linear infinite',
        marquee: 'marquee 50s linear infinite',
        'rotate-always': 'rotateAlways 10s linear infinite',
      },
      keyframes: {
        letterMove: {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '50%': { transform: 'translate(-50px, -50px)' },
        },
        blink: {
          '0%, 100%': { opacity: 0 },
          '50%': { opacity: 1 },
        },
        rotateBlink: {
          '0%': { opacity: 0, transform: 'rotate(0deg)' },
          '50%': { opacity: 1, transform: 'rotate(180deg)' },
          '100%': { opacity: 0, transform: 'rotate(360deg)' },
        },
        shake: {
          '10%, 90%': { transform: 'translateX(-1px)' },
          '20%, 80%': { transform: 'translateX(5px)' },
          '30%, 50%, 70%': { transform: 'translateX(-9px)' },
          '40%, 60%': { transform: 'translateX(9px)' },
        },
        rotate15x: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(5400deg)' }, // 360 degrees * 15
        },
        marquee: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        rotateAlways: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
      colors: {
        dark: '#1E1E20',
        light: '#FFFFFF',
        chill: '#F5F2D9',
        verified: '#F5AF26',
        love: '#FEAFE7',
        'fill-love': '#ED04AD',
        hate: '#D4D2C7',
        'fill-hate': '#18181A',
        menu: '#F6DE05',
        'fill-menu': '#18181A',
        search: '#CCEE2C',
        'fill-search': '#18181A',
        back: '#FFFFFF',
        'fill-back': '#18181A',
        action: '#F5F2D9',
        'main-match-card-bg': '#AFD1A6',
        'test': '#d3e5cd',
        footer: '#BFA1FF',
        cardBg1: '#D5F4E9',
        cardBg2: '#F5D6AF',
        cardBg3: '#E8CDFE',
        cardBg4: '#E2EDFD',
        portfoGreenBG: '#adff93',
        portfoGreentBGsmall: '#abff93',
        portfoGreentStar: '#b2ff96',
        portfoBlueBG: '#9cc1ff',
        portfoBlueCardBG: '#9cc2ff',
        portfoDirtyWhiteText: '#fde9de',
        portfoDirtyYellowWhite: '#fff3cd',
        portfoYellowBG: '#fdd85e',
        portfoOrangeCardBG: '#ffb040',
        portfoYellowCardBG: '#fdd85e',
        portfoYellowDirtyCardBG: '#fdf6e3',
        portfoRedBG: '#ff9388',
        portfoRedLightBG: '#ffe9df',
        portfoPurpleCardBG: '#c0befd',
        portfoPinkCardBG: '#ff80ba',
        portfoPinkBG: '#f66fb8',
        'solarized-red': '#dc322f',
        'solarized-blue': '#258bd2',
        'solarized-green': '#859901',
        'solarized-magenta': '#d23682',
        'solarized-yellow': '#b58901',
        'solarized-violet': '#6c71c4',
      },
    },
  },
  plugins: [],
};
